# Generated by Django 4.1.7 on 2023-04-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dept",
            fields=[
                (
                    "d_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emp",
            fields=[
                (
                    "e_name",
                    models.CharField(max_length=33, primary_key=True, serialize=False),
                ),
                ("e_no", models.IntegerField()),
                (
                    "d_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.dept"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                ("sal", models.IntegerField()),
                ("gender", models.CharField(max_length=21)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "e_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.emp"
                    ),
                ),
            ],
        ),
    ]
